# Generated by Django 4.1.2 on 2022-11-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_delete_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='StudentID',
            new_name='mob',
        ),
    ]
