# Generated by Django 4.1.2 on 2022-12-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_studentid_profile_mob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mob',
            new_name='StudentID',
        ),
    ]
