# Generated by Django 4.1.2 on 2022-12-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
