# Generated by Django 4.1.2 on 2022-12-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='StudentID',
            field=models.PositiveIntegerField(),
        ),
    ]
