# Generated by Django 4.1.2 on 2022-12-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favourite',
            new_name='favorite',
        ),
    ]
