# Generated by Django 4.1.2 on 2022-12-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docfile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pdf',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='document2',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
