# Generated by Django 4.1.2 on 2022-12-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_document_docfile_remove_post_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=75)),
                ('website', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('document', models.FileField(null=True, upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
