# Generated by Django 4.1.2 on 2022-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_comment_document_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(null=True, upload_to='books'),
        ),
    ]
