# Generated by Django 4.1.2 on 2022-12-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_document_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
