# Generated by Django 4.1.2 on 2022-12-10 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_document_date_posted_remove_document_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.FileField(null=True, upload_to='notes/'),
        ),
        migrations.AddField(
            model_name='document',
            name='questionpaper',
            field=models.FileField(null=True, upload_to='questionpaper/'),
        ),
    ]
