# Generated by Django 4.1.2 on 2022-12-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='document',
            name='questionpaper',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(default='Books', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
