# Generated by Django 4.1.2 on 2022-12-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_document_notes_remove_document_pdf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='pdf',
        ),
    ]
