# Generated by Django 4.1.2 on 2022-12-13 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Likes',
        ),
        migrations.AddField(
            model_name='document',
            name='Likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
