# Generated by Django 4.1.2 on 2022-12-28 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_remove_post_likes_document_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourtie', to=settings.AUTH_USER_MODEL),
        ),
    ]
