# Generated by Django 4.1.2 on 2022-12-30 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_document_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='favourite',
        ),
        migrations.AddField(
            model_name='document',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
