# Generated by Django 4.1.2 on 2023-02-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_document_favourite_document_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Field7',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
