# Generated by Django 4.1.2 on 2022-12-30 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_remove_document_favourite_document_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
