# Generated by Django 4.1.2 on 2023-02-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_document_favourites'),
        ('blog', '0022_document_field7'),
    ]

    operations = [
    ]
