# Generated by Django 4.1.2 on 2023-02-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_merge_20230223_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='Field7',
        ),
    ]
