# Generated by Django 4.1.2 on 2023-02-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_course_stream_year_document2_course_document2_stream_and_more'),
    ]

    operations = [
    migrations.DeleteModel(
    name='Stream',
    ),

    ]
