# Generated by Django 4.1.2 on 2023-02-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20230224_2008'),
    ]

    operations = [
    ]
