# Generated by Django 4.1.2 on 2023-02-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document2',
            name='stream',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
