# Generated by Django 4.1.2 on 2023-02-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_delete_category_remove_post_author_delete_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document2',
            name='likes',
        ),
    ]
